### ISSUE TITLE
Swipes starting at edges (x or y === 0) are disregarded

### ISSUE THREAD

**Issue by merrywhether** [FormidableLabs/react-swipeable#182]
**Describe the bug**
Swipes originating from coordinates with x = 0 (left edge) or y = 0 (top edge) will not be captured. I only found this by writing tests against my usage of this library as I believe this behavior is really hard to replicate in real world use cases. It's caused by a improper falsy check on this line:
https://github.com/FormidableLabs/react-swipeable/blob/master/src/index.js#L73

I think it should be:
```ts
if (state.xy[0] === undefined || state.xy[1] === undefined || ...
```

**Steps or Sandbox to reproduce**
In my tests I have
```ts
    act(() => {
      // swipe down
      document.dispatchEvent(
        new TouchEvent('touchstart', {
          touches: [
            {
              clientX: 1,
              clientY: 1,
            } as any,
          ],
        }),
      );
      document.dispatchEvent(
        new TouchEvent('touchmove', {
          touches: [
            {
              clientX: 1,
              clientY: 20,
            } as any,
          ],
        }),
      );
      document.dispatchEvent(
        new TouchEvent('touchend', {
          touches: [
            {
              clientX: 1,
              clientY: 20,
            } as any,
          ],
        }),
      );
    });
    expectOnlyHandlerCalled(initialProps.inputHandler, 'onSwipe');
    expect(initialProps.inputHandler.onSwipe).toHaveBeenCalledWith('Down');
```

As-is, the test passes. But if I change all of the `clientX` values to 0 (or the initial `clientY` value to 0), the test fails because no swipe was detected, with the code bailing out in `onMove` at that if-check.

**Expected behavior**
Since the screen is a 0-based grid, it seems like touches starting on the edges should be handled?

**Comment by hartzis** [comment]
@merrywhether nice find. This has existed since this libraries inception.

You're totally right that the actual likelihood that a real user has somehow started a swipe at `0` is extremely low.

I do believe your investigation is correct for where the bug is happening.
https://github.com/FormidableLabs/react-swipeable/blob/939ee9fdbc108e07af4ac1dfc5739f2db1a6f7d4/src/index.js#L73

We also need to update the `initialState.xy` here to be `[]`.
https://github.com/FormidableLabs/react-swipeable/blob/939ee9fdbc108e07af4ac1dfc5739f2db1a6f7d4/src/index.js#L12-L13

Please feel free to create a PR if you'd like. If not I may be able to get around to this soonish, but my current priorities are working on [v6](https://github.com/FormidableLabs/react-swipeable/projects/2)

**Comment by hartzis** [comment]
Coming in v6
