### ISSUE TITLE
prevent swipe event from bubbling up with nested swipeables

### ISSUE THREAD

**Issue by jwasden** [FormidableLabs/react-swipeable#219]
This is probably a simple thing that I'm missing, but is there a way to prevent swipe events in a child from bubbling up to a parent? They both have swipe functionality, but when I swipe in a child, it swipes both the parent and the child, which is not what I'm looking for. 

I reflexively was looking for some kind of stopPropagation in the handlers, but didn't find it there.

Thoughts?

https://codesandbox.io/s/react-swipeable-image-carousel-forked-hcewd

**Comment by jwasden** [comment]
I found a solution for what I was looking for: I used a ternary to check if I wanted to run the parent effect or not. This seems to work just fine. Example below.

```javascript
const [parentCondition, setParentCondition] = useState(false); // set and control this as you see fit to prevent the parent from executing
const config = {
// whatever you fancy per the docs
}
const parentHandlers = useSwipeable({
  // onSwiped: (eventData) => console.log("swiped", eventData),
  onSwipedLeft: () => parentCondition ? null : someFunc(),
  onSwipedRight: () => parentCondition ? null : someFunc(),
  ...config
});
```

**Comment by hartzis** [comment]
@jwasden Thank you for the great issue and incredibly helpful codesandbox example!

I think this issue came up a few years ago and we created a prop called `stopPropagation` to call `event.stopPropagation` on the swipe event.

But i gave this a whirl in your example and it didn't quite work, **but** a different method did work, [event.stopImmediatePropagation();](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopImmediatePropagation

Example: https://codesandbox.io/s/react-swipeable-image-carousel-forked-5bqbv?file=/src/Carousel.js:1156-1196

---
###📓 Side note on your solution 

Glad you found a way to get it to work.

I dont know how or when you're calling `setParentCondition`, but if it is in the child's `onSwiping` may i recommend using a `ref` instead, as the state is not needed to actually "render" anything.

```
const childSwiping = useRef(false);

const parentHandlers = useSwipeable({
  onSwipedLeft: () => childSwiping.current ? null : someFunc(),
  onSwipedRight: () => childSwiping.current ? null : someFunc(),
  ...config
});

const childHandlers = useSwipeable({
  onSwipedLeft: () => { someFunc(); childSwiping.current = false; },
  onSwipedRight: () => { someFunc(); childSwiping.current = false; },
  onSwiping: () => { childSwiping.current = true; },
  ...config
});
```

Cheers and thank you again for the great issue!

**Comment by jwasden** [comment]
Thanks for the reply and the example back. I'll give that event.stopImmediatePropogation() approach a go; it's a bit more clear about what's happening, I think.

Cheers. :)
