### ISSUE TITLE
Swiping does not work on iframe

### ISSUE THREAD

**Issue by jmorey28** [FormidableLabs/react-swipeable#257]
We have an image carousel with video iframes and react-swipeable does not detect swiping on the iframe.

**Comment by hartzis** [comment]
@jmorey28 thank you for the issue. I'd love to see an example of what you're referring to.

Do you think you could setup a small codesandbox.io example by chance?

I know `react-swipeable` can work inside an iframe, our example page used to have iframes embedded from codesandbox, but it sounds like you may be referring to a carousel of iframes?

**Comment by westmark** [comment]
If @jmorey28  is referring to swiping ON a iframe(which I think is the case) rather than INSIDE an iframe, then I have the same issue. Due to the security model in most (if not all) modern browsers the iframe will eat all touch/mouse-events and won't allow anything to bubble up to the parent document.

The easy solution is just to overlay the iframe with some element of the same size, but since my iframe has links and scrollbars that won't work. Instead I sacrificed some space at the bottom of the viewport and added a thin overlay where the user can swipe.

**Comment by hartzis** [comment]
@westmark great info!

Also found some supporting info on stackoverflow
- https://stackoverflow.com/questions/3690812/capture-click-on-div-surrounding-an-iframe

Also found a possible neat trick that sounds similar to what you're attempting @jmorey28 
- https://stevenwaller.io/articles/prevent-iframes-from-eating-touch-events-in-ios/

Let us know if that works.
